name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    runs-on: ubuntu-latest
    container: osgeo/grass-gis:releasebranch_8_4-ubuntu
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y ca-certificates

    - uses: actions/checkout@v5

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install
      run: |
        uv venv
        uv pip install -e .

    - name: Run tests
      run: |
        uv run pytest --random-order
